app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^job$', views.job, name="job"),
    url(r'^division$', views.division, name="division"),
    url(r'^standard$', views.standard, name="standard"),
    url(r'^patchStandard$', views.patchStandard, name="patchStandard"),
    url(r'^patchTolerance$', views.patchTolerance, name="patchTolerance"),
    url(r'^role$', views.role, name="role"),
    url(r'^bookmark$', views.bookmark, name="bookmark"),
    url(r'^link$', views.link, name="link"),
    url(r'^upload$', views.upload, name="upload"),

    url(r'^valuesFromBrand$', views.valuesFromBrand, name="valuesFromBrand"),

    url(r'^showJobs$', views.showJobs, name="showJobs"),
    url(r'^showBrands$', views.showBrands, name="showBrands"),
    url(r'^showDivisions$', views.showDivisions, name="showDivisions"),
    url(r'^showStandards$', views.showStandards, name="showStandards"),
    url(r'^showEvalutions$', views.showEvalutions, name="showEvalutions"),
    url(r'^showMemberEvaluations$', views.showMemberEvaluations, name="showMemberEvaluations"),
    url(r'^showMemberProperty$', views.showMemberProperty, name="showMemberProperty"),
    url(r'^showUploads$', views.showUploads, name="showUploads"),

    url(r'^editJob/(?P<ID>\d+)$', views.editJob, name="editJob"),
    url(r'^editDivision/(?P<ID>\d+)$', views.editDivision, name="editDivision"),
    url(r'^editStandard/(?P<ID>\d+)$', views.editStandard, name="editStandard"),
    url(r'^editUpload/(?P<ID>\d+)$', views.editUpload, name="editUpload"),

    url(r'^deleteJob/(?P<ID>\d+)$', views.deleteJob, name="deleteJob"),
    url(r'^deleteBrand/(?P<ID>\d+)$', views.deleteBrand, name="deleteBrand"),
    url(r'^deleteDivision/(?P<ID>\d+)$', views.deleteDivision, name="deleteDivision"),
    url(r'^deleteStandard/(?P<ID>\d+)$', views.deleteStandard, name="deleteStandard"),
    url(r'^deleteUpload/(?P<ID>\d+)$', views.deleteUpload, name="deleteUpload"),


]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("app.urls", namespace="app")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/division.html
{% extends "base.html" %} {% load staticfiles %} {% block title %} Home {% endblock title %} {% block content %}
<div class="row" style="margin-top:-20px">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <div class="box palette-Grey-300 bg">
          <div class="box-header  palette-Grey-300 bg">
            <h3 class="box-title"><span class="text-white">&nbsp;&nbsp;&nbsp;NEW DIVISION</span></h3>
            <div class="pull-right text-white box-tools">
              <span class="text-white box-btn"><i class="circle-nest-medium ti-notepad"></i>
              </span> &nbsp;&nbsp;&nbsp;
            </div>
            <div class="medium-9 columns ">
              <div>
                <form action="#" method="POST" class="form-inline">{% csrf_token %}
                  <br>
                  <br>
                  <h4 style="color: red">{{message}}</h4>

                  <div class="form-group">
                    <label  >Member Name:</label>
                    <select name="member" class="form-control">
                      {%for each in members %}
                        <option value={{each.pk}}>{{each.name}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="form-group">
                    <label >Division Name:</label>
                    <input type="text" class="form-control" name="name" required></input>
                  </div>
                  <div class="form-group">
                    <label >Address:</label>
                    <input type="text" class="form-control" name="address" required></input>
                  </div>
                  <div class="form-group">
                    <label >City:</label>
                    <input type="text" class="form-control" name="city" required></input>
                  </div>
                  <div class="form-group">
                    <label >State:</label>
                    <input type="text" class="form-control" name="state" required></input>
                  </div>
                  <div class="form-group">
                    <label >Country:</label>
                    <select name="country" class="form-control">
                      <option disabled selected value> -- select an option -- </option>
                      {%for each in countries %}
                        <option value={{each.0}}>{{each.1}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label >ZIP:</label>
                    <input type="text" class="form-control" name="zip" required></input>
                  </div>

                  <button type="submit" class="btn btn-default">Create Division</button>

                  <br>
                  <br>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/app/editDivision.html
{% extends "base.html" %} {% load staticfiles %} {% block title %} Edit Division {% endblock title %} {% block content %}
<div class="row" style="margin-top:-20px">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <div class="box palette-Grey-300 bg">
          <div class="box-header  palette-Grey-300 bg">
            <h3 class="box-title"><span class="text-white">&nbsp;&nbsp;&nbsp;EDIT DIVISION</span></h3>
            <div class="pull-right text-white box-tools">
              <span class="text-white box-btn"><i class="circle-nest-medium ti-notepad"></i>
              </span> &nbsp;&nbsp;&nbsp;
            </div>
            <div class="medium-9 columns ">
              <div>
                <form action="#" method="POST" class="form-inline">{% csrf_token %}
                  <br>
                  <br>
                  <h4 style="color: red">{{message}}</h4>

                  <div class="form-group">
                    <label>Member Name:</label>
                    <select name="member" class="form-control">
                      {%for each in members %}
                        {% if each == division.member %}
                          <option value={{each.pk}} selected>{{each.name}}</option>
                        {% else %}
                          <option value={{each.pk}}>{{each.name}}</option>
                        {% endif %}
                        <option value={{each.pk}}>{{each.name}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="form-group">
                    <label>Division Name:</label>
                    <input type="text" class="form-control" name="name" value="{{division.name}}" required></input>
                  </div>
                  <div class="form-group">
                    <label>Address:</label>
                    <input type="text" class="form-control" name="address" value="{{division.address}}" required></input>
                  </div>
                  <div class="form-group">
                    <label>City:</label>
                    <input type="text" class="form-control" name="city" value="{{division.city}}" required></input>
                  </div>
                  <div class="form-group">
                    <label>State:</label>
                    <input type="text" class="form-control" name="state" value="{{division.state}}" required></input>
                  </div>
                  <div class="form-group">
                    <label>Country:</label>
                    <select name="country" class="form-control">
                      {%for each in countries %}
                        {% if each.0 == division.country %}
                          <option value={{each.0}} selected>{{each.1}}</option>
                        {% else %}
                          <option value={{each.0}}>{{each.1}}</option>
                        {% endif %}
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>ZIP:</label>
                    <input type="text" class="form-control" name="zip" value="{{division.zipCode}}" required></input>
                  </div>

                  <button type="submit" class="btn btn-default">Update Division</button>

                  <br>
                  <br>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/app/editJob.html
{% extends "base.html" %} {% load staticfiles %} {% block title %} Edit Job {% endblock title %} {% block content %}
<div class="row" style="margin-top:-20px">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <div class="box palette-Grey-300 bg">
          <div class="box-header  palette-Grey-300 bg">
            <h3 class="box-title"><span class="text-white">&nbsp;&nbsp;&nbsp;Edit Job</span></h3>
            <div class="pull-right text-white box-tools">
              <span class="text-white box-btn"><i class="circle-nest-medium ti-notepad"></i>
              </span> &nbsp;&nbsp;&nbsp;
            </div>
            <div class="medium-9 columns ">
              <div>

                <script>
                  //used below for maitaining Color List coun
                  var colorCount = 0;
                  var brand = "";
                  var patchStandards;
                  var patchTolerances;
                </script>

                <script>
                  function report(value) {
                    brand = value;
                    console.log("value=", value);
                    if (value == "") return; // please select - possibly you want something else he
                    else {
                      $.get("{%url "app:valuesFromBrand" %}", {"brand": value},
                        function(values) {
                          divisions = {{divisions}}
                          console.log("values=", values, " divisions=", divisions);

                          $('#divisionOptions option').remove();
                          for (var count = 0; count < values["divisions"].length; count++) {
                            if(divisions.indexOf(values["divisions"][count]["id"]) > -1 && {{job.brand.id}} == brand){
                              $('#divisionOptions').append('<option value=' + values["divisions"][count]["id"] + ' selected>' + values["divisions"][count]["name"] + '</option>');
                            }
                            else{
                              $('#divisionOptions').append(new Option(values["divisions"][count]["name"], values["divisions"][count]["id"]));
                            }

                          }

                          $('#productOptions option').remove();
                          $('#productOptions').append('<option disabled selected value> -- select an option -- </option>')
                          for (var count = 0; count < values["products"].length; count++) {
                            var id = (values["products"][count]["id"]).toString();
                            if (id.localeCompare("{{job.product.id}}") == 0) {
                              $('#productOptions').append('<option value=' + values["products"][count]["id"] + ' selected>' + values["products"][count]["name"] + '</option>')
                            }
                            else {
                              $('#productOptions').append(new Option(values["products"][count]["name"], values["products"][count]["id"]));
                            }
                          }

                          patchStandards = values["patchStandards"];
                          patchTolerances = values["patchTolerances"];
                          patchSta = {{patchSta}};
                          patchTol = {{patchTol}};

                          $('select[name^=brandColor] option').remove();
                          $('select[name^=patchTolerance] option').remove();
                          $('select[name^=patchTolerance]').append('<option disabled selected value> -- select an option -- </option>');
                          $('select[name^=brandColor]').append('<option disabled selected value> -- select an option -- </option>');

                          for(var count=0; count < patchStandards.length; count++){
                            $('select[name^=brandColor]').append(new Option(patchStandards[count]["name"], patchStandards[count]["id"]));
                          }
                          for(var count=0; count < patchTolerances.length; count++){
                            $('select[name^=patchTolerance]').append( new Option(values["patchTolerances"][count]["name"],values["patchTolerances"][count]["id"]) );
                          }
                          if({{job.brand.id}} == brand){
                            for(var count=1; count <= patchSta.length; count++){
                                $('select[name=brandColor'+count+']').val(patchSta[count-1])
                                .find("option[value=" + patchSta[count-1] +"]").attr('selected', true);
                                $('select[name=patchTolerance'+count+']').val(patchTol[count-1])
                                .find("option[value=" + patchTol[count-1] +"]").attr('selected', true);
                            }
                          }

                        }).fail(function() {
                        console.log("error");
                      });
                    }
                  }
                </script>

                <form action="#" method="POST" class="form-inline">{% csrf_token %}
                  <br>
                  <br>
                  <h4 style="color: red">{{message}}</h4>

                  <div class="form-group">

                    <label>Brand Name:</label>
                    <select name="brand" class="form-control" onchange="report(this.value)">
                      {%for each in brands %}
                          {% if each.id == job.brand.id %}
                            <option value={{each.pk}} selected>{{each.name}}</option>
                          {% else %}
                            <option value={{each.pk}}>{{each.name}}</option>
                          {% endif %}
                      {% endfor %}
                    </select>
                  </div>

                  <div class="form-group">
                    <label>Product Name:</label>
                    <select id="productOptions" name="product"  class="form-control" required>

                    </select>
                  </div>

                  <div class="form-group">
                    <label>Division Name:</label>
                    <select id="divisionOptions" name="divisions" multiple class="form-control" required>
                    </select>
                  </div>

                  <div class="form-group">
                    <label >Job Name:</label>
                    <input type="text" class="form-control" name="jobName" value="{{job.name}}"required>
                  </div>

                  <div class="form-group">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>Color List</th>
                          <th>Brand Color</th>
                          <th>Patch Tolerance</th>
                          <th>
                            <button type="button" class="btn btn-default" onclick="fieldAdd();"><span>Add</span></button>
                            <button type="button" class="btn btn-default" onclick="fieldRemove();"><span>Remove</span></button>
                          </th>

                        </tr>
                      </thead>

                      <script>
                        function fieldAdd() {
                          colorCount+=1;
                          document.getElementById('countOfColor').value = colorCount;
                          $('#addTable').append(
                            `<tr>
                              <td><label  name='colorListLable`+colorCount+`'>Color List `+colorCount+`</label></td>
                              <td><select required id='brandColorOptions`+colorCount+`' name='brandColor`+colorCount+`' class='form-control'></select></td>
                              <td><select required id='patchToleranceOptions`+colorCount+`' name='patchTolerance`+colorCount+`' class='form-control'></select></td>
                              <td></td>
                            </tr>`
                          )
                          $('select[name^=brandColor'+colorCount+']').append('<option disabled selected value> -- select an option -- </option>');
                          for(var count=0; count < patchStandards.length; count++){
                          //  console.log("patchStandards",patchStandards[count]["id"], patchStandards[count]["name"] );
                           $('select[name^=brandColor'+colorCount+']').append( new Option(patchStandards[count]["name"],patchStandards[count]["id"]) );
                          }

                          $('select[name^=patchTolerance'+colorCount+']').append('<option disabled selected value> -- select an option -- </option>');
                          for(var count=0; count < patchTolerances.length; count++){
                            //  console.log("patchTolerances",patchTolerances[count]["id"], patchTolerances[count]["name"] );
                           $('select[name^=patchTolerance'+colorCount+']').append( new Option(patchTolerances[count]["name"],patchTolerances[count]["id"]) );
                          }


                        }
                      </script>
                      <script>
                        function fieldRemove() {
                          if(colorCount!=1){
                            colorCount-=1;
                            document.getElementById('countOfColor').value = colorCount;
                            $('#addTable tr').last().remove()
                          }
                          return false;

                        }
                      </script>

                      <tbody id="addTable">
                        {% for each in jobPatch  %}
                          <tr>
                            <td><label  name="colorListLable{{forloop.counter}}">Color List {{forloop.counter}}</label></td>
                            <td>
                              <select required id="brandColorOptions{{forloop.counter}}" name="brandColor{{forloop.counter}}" class="form-control">
                              </select>
                            </td>
                            <td>
                              <select required id="patchToleranceOptions{{forloop.counter}}" name="patchTolerance{{forloop.counter}}" class="form-control">
                              </select>
                            </td>
                            <td></td>
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>

                    <input type="hidden" id="countOfColor" name="countOfColor" value="">

                    <script type="text/javascript">
                      colorCount={{jobPatch|length}};
                      document.getElementById('countOfColor').value = colorCount;
                    </script>



                    <label>Active:</label>
                    <select name="active" class="form-control" required>
                      {% if job.active == 1 %}
                        <option selected value="True">Active</option>
                        <option value="False">Inactive</option>
                      {% else %}
                      <option value="True">Active</option>
                      <option selected value="False">Inactive</option>
                      {% endif %}
                    </select>
                  </div>

                  <button type="submit" class="btn btn-default">Update Job</button>

                  <br>
                  <br>
                </form>
              </div>
              <script type='text/javascript' src="{% static "js/jquery.js" %}"></script>
              <script type="text/javascript">
                $( document ).ready(function(){
                  report({{job.brand.id}});
                });
              </script>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/app/job.html
{% extends "base.html" %} {% load staticfiles %} {% block title %} New Job {% endblock title %} {% block content %}
<div class="row" style="margin-top:-20px">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <div class="box palette-Grey-300 bg">
          <div class="box-header  palette-Grey-300 bg">
            <h3 class="box-title"><span class="text-white">&nbsp;&nbsp;&nbsp;NEW JOB</span></h3>
            <div class="pull-right text-white box-tools">
              <span class="text-white box-btn"><i class="circle-nest-medium ti-notepad"></i>
              </span> &nbsp;&nbsp;&nbsp;
            </div>
            <div class="medium-9 columns ">
              <div>

                <script>
                  //used below for maitaining Color List coun
                  var colorCount=1;
                  var brand = "";
                  var patchStandards;
                  var patchTolerances;
                </script>

                <script>
                  function report(value) {
                    brand=value;
                    if (value=="") return; // please select - possibly you want something else here
                    else{
                      $.get("{%url "app:valuesFromBrand" %}", { "brand": value },
                          function(values){
                              console.log("values=", values);
                               $('#divisionOptions option').remove();
                               for(var count=0; count < values["divisions"].length; count++){
                                 //  console.log("values",divisions["divisions"][count]["id"] );
                                $('#divisionOptions').append( new Option(values["divisions"][count]["name"],values["divisions"][count]["id"]) );
                               }

                               $('#productOptions option').remove();
                               for(var count=0; count < values["products"].length; count++){
                                 //  console.log("values",divisions["divisions"][count]["id"] );
                                $('#productOptions').append( new Option(values["products"][count]["name"],values["products"][count]["id"]) );
                               }

                              $('select[name^=brandColor] option').remove();
                              patchStandards = values["patchStandards"];
                              $('select[name^=brandColor]').append('<option disabled selected value> -- select an option -- </option>');
                              for(var count=0; count < values["patchStandards"].length; count++){
                              //  console.log("patchStandards",values["patchStandards"][count]["id"], values["patchStandards"][count]["name"] );
                               $('select[name^=brandColor]').append( new Option(values["patchStandards"][count]["name"],values["patchStandards"][count]["id"]) );
                              }

                              $('select[name^=patchTolerance] option').remove();
                              patchTolerances = values["patchTolerances"];

                              $('select[name^=patchTolerance]').append('<option disabled selected value> -- select an option -- </option>');
                              for(var count=0; count < values["patchTolerances"].length; count++){
                                //  console.log("patchTolerances",values["patchTolerances"][count]["id"], values["patchTolerances"][count]["name"] );
                               $('select[name^=patchTolerance]').append( new Option(values["patchTolerances"][count]["name"],values["patchTolerances"][count]["id"]) );
                              }

                      }).fail(function(){
                          console.log("error");
                      });
                    }
                  }
                </script>

                <form action="#" method="POST" class="form-inline">{% csrf_token %}
                  <br>
                  <br>
                  <h4 style="color: red">{{message}}</h4>

                  <div class="form-group">

                    <label>Brand Name:</label>
                    <select name="brand" class="form-control" onchange="report(this.value)">
                      <option disabled selected value> -- select an option -- </option>
                      {%for each in brands %}
                        <option value={{each.pk}}>{{each.name}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="form-group">
                    <label>Product Name:</label>
                    <select id="productOptions" name="product"  class="form-control" required>
                      <option disabled selected value> -- select an option -- </option>
                    </select>
                  </div>

                  <div class="form-group">
                    <label>Division Name:</label>
                    <select id="divisionOptions" name="divisions" multiple class="form-control" required>
                    </select>
                  </div>

                  <div class="form-group">
                    <label >Job Name:</label>
                    <input type="text" class="form-control" name="jobName" required>
                  </div>

                  <div class="form-group">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>Color List</th>
                          <th>Brand Color</th>
                          <th>Patch Tolerance</th>
                          <th>
                            <button type="button" class="btn btn-default" onclick="fieldAdd();"><span>Add</span></button>
                            <button type="button" class="btn btn-default" onclick="fieldRemove();"><span>Remove</span></button>
                          </th>

                        </tr>
                      </thead>

                      <script>
                        function fieldAdd() {
                          colorCount+=1;
                          document.getElementById('countOfColor').value = colorCount;
                          $('#addTable').append(
                            `<tr>
                              <td><label  name='colorListLable`+colorCount+`'>Color List `+colorCount+`</label></td>
                              <td><select required id='brandColorOptions`+colorCount+`' name='brandColor`+colorCount+`' class='form-control'></select></td>
                              <td><select required id='patchToleranceOptions`+colorCount+`' name='patchTolerance`+colorCount+`' class='form-control'></select></td>
                              <td></td>
                            </tr>`
                          )
                          $('select[name^=brandColor'+colorCount+']').append('<option disabled selected value> -- select an option -- </option>');
                          for(var count=0; count < patchStandards.length; count++){
                          //  console.log("patchStandards",patchStandards[count]["id"], patchStandards[count]["name"] );
                           $('select[name^=brandColor'+colorCount+']').append( new Option(patchStandards[count]["name"],patchStandards[count]["id"]) );
                          }

                          $('select[name^=patchTolerance'+colorCount+']').append('<option disabled selected value> -- select an option -- </option>');
                          for(var count=0; count < patchTolerances.length; count++){
                            //  console.log("patchTolerances",patchTolerances[count]["id"], patchTolerances[count]["name"] );
                           $('select[name^=patchTolerance'+colorCount+']').append( new Option(patchTolerances[count]["name"],patchTolerances[count]["id"]) );
                          }


                        }
                      </script>
                      <script>
                      function fieldRemove() {
                        if(colorCount!=1){
                          document.getElementById('countOfColor').value = colorCount;
                          colorCount-=1;
                          $('#addTable tr').last().remove()
                        }
                        return false;

                      }

                      </script>

                      <tbody id="addTable">
                        <tr>
                          <td><label  name="colorListLable1">Color List 1</label></td>
                          <td><select required id="brandColorOptions1" name="brandColor1" class="form-control">
                                <option disabled selected value> -- select an option -- </option>
                              </select>
                          </td>
                          <td><select required id="patchToleranceOptions1" name="patchTolerance1" class="form-control">
                                <option disabled selected value> -- select an option -- </option>
                              </select>
                          </td>
                          <td></td>
                        </tr>

                      </tbody>
                    </table>

                    <input type="hidden" id="countOfColor" name="countOfColor" value="">
                    <script type="text/javascript">
                      document.getElementById('countOfColor').value = colorCount;
                    </script>



                    <label>Active:</label>
                    <select name="active" class="form-control" required>
                          <option value="True">Active</option>
                          <option value="False">Inactive</option>
                    </select>
                  </div>



                  <button type="submit" class="btn btn-default">Create Job</button>

                  <br>
                  <br>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}