app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^job$', views.job, name="job"),
    url(r'^division$', views.division, name="division"),
    url(r'^standard$', views.standard, name="standard"),
    url(r'^patchStandard$', views.patchStandard, name="patchStandard"),
    url(r'^patchTolerance$', views.patchTolerance, name="patchTolerance"),
    url(r'^role$', views.role, name="role"),
    url(r'^bookmark$', views.bookmark, name="bookmark"),
    url(r'^link$', views.link, name="link"),
    url(r'^upload$', views.upload, name="upload"),

    url(r'^valuesFromBrand$', views.valuesFromBrand, name="valuesFromBrand"),

    url(r'^showJobs$', views.showJobs, name="showJobs"),
    url(r'^showBrands$', views.showBrands, name="showBrands"),
    url(r'^showDivisions$', views.showDivisions, name="showDivisions"),
    url(r'^showStandards$', views.showStandards, name="showStandards"),
    url(r'^showEvalutions$', views.showEvalutions, name="showEvalutions"),
    url(r'^showMemberEvaluations$', views.showMemberEvaluations, name="showMemberEvaluations"),
    url(r'^showMemberProperty$', views.showMemberProperty, name="showMemberProperty"),
    url(r'^showUploads$', views.showUploads, name="showUploads"),

    url(r'^editJob/(?P<ID>\d+)$', views.editJob, name="editJob"),
    url(r'^editDivision/(?P<ID>\d+)$', views.editDivision, name="editDivision"),
    url(r'^editStandard/(?P<ID>\d+)$', views.editStandard, name="editStandard"),
    url(r'^editUpload/(?P<ID>\d+)$', views.editUpload, name="editUpload"),

    url(r'^deleteJob/(?P<ID>\d+)$', views.deleteJob, name="deleteJob"),
    url(r'^deleteBrand/(?P<ID>\d+)$', views.deleteBrand, name="deleteBrand"),
    url(r'^deleteDivision/(?P<ID>\d+)$', views.deleteDivision, name="deleteDivision"),
    url(r'^deleteStandard/(?P<ID>\d+)$', views.deleteStandard, name="deleteStandard"),
    url(r'^deleteUpload/(?P<ID>\d+)$', views.deleteUpload, name="deleteUpload"),


]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("app.urls", namespace="app")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %} | Smiley Color and Associates</title>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}" />
    <link rel="stylesheet" href="{% static "css/palette.css" %}">
    <link rel="stylesheet" href="{% static "sass/css/dashboard.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/dripicon.css" %}">
    <link rel="stylesheet" href="{% static "css/typicons.css" %}" />
    <link rel="stylesheet" href="{% static "css/font-awesome.css" %}" />
    <link rel="stylesheet" href="{% static "css/themify-icons.css" %}" />
    <link rel="stylesheet" href="{% static "css/Montserrat-Hairline.css" %}" />
    <link rel="stylesheet" href="{% static "sass/css/theme.css" %}">
    <link rel="stylesheet" href="{% static "css/login.css" %}">

    <script src="{% static "js/pace/pace.js" %}"></script>
    <link href="{% static "js/pace/themes/orange/pace-theme-flash.css" %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static "js/slicknav/slicknav.css" %}" />
    <script src="{% static "js/vendor/modernizr.js" %}"></script>
</head>

<body>
  <div class="wrapper">

        {% include "header.html" %}

        {% block content %}
        {% endblock content %}

        {% include "footer.html" %}

  </div>

  <script type='text/javascript' src="{% static "js/jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "js/waypoints.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/preloader-script.js" %}"></script>
  <script type='text/javascript' src="{% static "js/what-input.js" %}"></script>
  <script type='text/javascript' src="{% static "js/foundation.js" %}"></script>
  <script type='text/javascript' src="{% static "js/foundation.min.js" %}"></script>
  {# <script type='text/javascript' src="{% static "js/foundation/foundation.dropdown.js" %}"></script> #}
  <script type='text/javascript' src="{% static "js/slimscroll/jquery.slimscroll.js" %}"></script>
  <script type='text/javascript' src="{% static "js/slicknav/jquery.slicknav.js" %}"></script>
  <script type='text/javascript' src="{% static "js/sliding-menu.js" %}"></script>
  <script type='text/javascript' src="{% static "js/scriptbreaker-multiple-accordion-1.js" %}"></script>
  <script type="text/javascript" src="{% static "js/circle-progress/jquery.circliful.js" %}"></script>
  <script type='text/javascript' src="{% static "js/number-progress-bar/jquery.velocity.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/number-progress-bar/number-pb.js" %}"></script>
  <script type='text/javascript' src="{% static "js/loader/loader.js" %}"></script>
  <script type='text/javascript' src="{% static "js/loader/demo.js" %}"></script>
  <script type='text/javascript' src="{% static "js/flot/jquery.flot.js" %}"></script>
  <script type='text/javascript' src="{% static "js/flot/jquery.flot.resize.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/flot/jquery.flot.pie.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/flot/jquery.flot.categories.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/skycons/skycons.js" %}"></script>
  <script type='text/javascript' src="{% static "js/app.js" %}"></script>
  <script type="text/javascript" src="{% static "js/number/jquery.counterup.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/gmap/gmap3.js" %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHt7vrI9b3Ze5nGXaCPrlaBzR-Saqg4G8"></script>




  <script>
      $(document).foundation();
  </script>

  <script type="text/javascript">
    $(function () {
      "use strict";
      $('#test').gmap3({
        center: [-7.39043726, 109.35286072]
        , zoom: 15
        , styles: [] //styles
      }).marker([
        {
          position: [-7.39043726, 109.35286072]
        }
        , {
          address: "Yogyakarta, Indonesia"
        }
        , {
          address: "Yogyakarta, Indonesia"
          , icon: "http://maps.google.com/mapfiles/marker_grey.png"
        }
      ]).on('click', function (marker) {
        marker.setIcon('../../maps.google.com/mapfiles/marker_green.png');
      });
      //weather icons
      var icons = new Skycons({
        "stroke": 0.06
        , "color": "Gray"
        , "cloudColor": "#666666"
        , "sunColor": "#92cd18"
        , "moonColor": "DodgerBlue"
        , "rainColor": "RoyalBlue"
        , "snowColor": "LightGray"
        , "windColor": "LightSteelBlue"
        , "fogColor": "#65C3DF"
      })
      , list = [
        "clear-day", "clear-night", "partly-cloudy-day"
        , "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind"
        , "fog"
      ]
      , i;
      for (i = list.length; i--;) icons.set(list[i], list[i]);
      icons.play()
      /*
      * LINE CHART
      * ----------
      */
      //LINE randomly generated data
      var line_data1 = [
        [1, 800]
        , [2, 1500]
        , [3, 900]
        , [4, 1900]
        , [5, 4000]
        , [6, 2800]
        , [7, 2500]
        , [8, 700]
        , [9, 1500]
        , [10, 1000]
        , [11, 2000]
        , [12, 4300]
        , [13, 1756]
        , [14, 2000]
        , [15, 1500]
        , [16, 1900]
        , [17, 1200]
        , [18, 2800]
        , [19, 3200]
        , [20, 2190]
      ];
      var line_data2 = [
        [1, 1800]
        , [2, 2900]
        , [3, 1950]
        , [4, 3450]
        , [5, 7000]
        , [6, 5300]
        , [7, 4890]
        , [8, 2300]
        , [9, 3900]
        , [10, 2900]
        , [11, 4500]
        , [12, 2200]
        , [13, 1120]
        , [14, 1459]
        , [15, 1100]
        , [16, 1189]
        , [17, 300]
        , [18, 1250]
        , [19, 1705]
        , [20, 959]

      ];
      $.plot("#line-chart", [line_data1, line_data2], {
        grid: {
          hoverable: true
          , borderColor: "#E2E6EE"
          , borderWidth: 0
          , labelMargin: 20
          , Margin: 1
          , aboveData: false
          , tickColor: "#E2E6EE"
        }
        ,
        series: {
          shadowSize: 0
          , bars: {
            show: true
            , lineWidth: 0
            , barWidth: 0.9
            , fill: 0.7
            , zero: true
          }
          , points: {
            show: false
          }
        }
        ,
        colors: ["#f20556", "#1565C0"]
        ,
        yaxis: {
          show: false
          ,
        }
        , xaxis: {
            show: true
            , position: "top"
        }
      });
        //Initialize tooltip on hover
        $("<div class='tooltip-inner' id='line-chart-tooltip'></div>").css({
          position: "absolute"
          , background: "#333333"
          , padding: "3px 10px"
          , color: "#ffffff"
          , display: "none"
          , opacity: 1
        }).appendTo("body");
        $("#line-chart").bind("plothover", function (event, pos, item) {
          if (item) {
            var x = item.datapoint[0].toFixed(2)
            , y = item.datapoint[1].toFixed(2);
            $("#line-chart-tooltip").html(item.series.label + " of " + x + " = " + y).css({
              top: item.pageY + 5
              , left: item.pageX + 5
            }).fadeIn(200);
          }
          else {
            $("#line-chart-tooltip").hide();
          }
        });

      });
  </script>

  <script type='text/javascript' src="{% static "js/gallery/jquery.easing.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/gallery/jquery.mixitup.min.js" %}"></script>
  <script type='text/javascript' src="{% static "js/gallery/jquery.swipebox.js" %}"></script>

  <script type="text/javascript">
      $(function () {
          //lightbox
          $('.swipebox').swipebox();
          //filtered portfolio
          var filterList = {
              init: function () {
                  // MixItUp plugin
                  // http://mixitup.io
                  $('#portfoliolist').mixitup({
                      targetSelector: '.portfolio'
                      , filterSelector: '.filter'
                      , effects: ['fade']
                      , easing: 'snap'
                      , // call the hover effect
                      onMixEnd: filterList.hoverEffect()
                  });
              }
              , hoverEffect: function () {
                  // Simple parallax effect
                  $('#portfoliolist .portfolio').hover(function () {
                      $(this).find('.label').stop().animate({
                          bottom: 0
                      }, 200, 'easeOutQuad');
                      $(this).find('img').stop().animate({
                          top: -30
                      }, 500, 'easeOutQuad');
                  }, function () {
                      $(this).find('.label').stop().animate({
                          bottom: -40
                      }, 200, 'easeInQuad');
                      $(this).find('img').stop().animate({
                          top: 0
                      }, 300, 'easeOutQuad');
                  });
              }
          };
          // Run the show!
          filterList.init();
      });
  </script>


</body>
</html>

templates/footer.html
{% load staticfiles %}

<!-- End of Widget  -->
<footer>
  <div id="footer">Copyright &copy; 2017 <a href="http://themeforest.net/user/dELHI NERDS">dELHI NERDS</a></div>
</footer>
</div>
<!-- End of Container Begin -->
<!-- Right Menu -->
<div class=" bg-transparent off-canvas position-right" id="offCanvas" data-off-canvas data-position="right">
  <!-- Close button -->
  <button class="close-button" aria-label="Close menu" type="button" data-close> <span aria-hidden="true">&times;</span> </button>
  <div class="off-canvas-content" data-off-canvas-content>
    <!-- Menu -->
    <ul class="nav navbar-stacked ">
      <li><a href="#"><span class="palette-Black-100 bg ti-menu-alt"></span>Notifications</a></li>
      <li><a href="#"><span class="palette-Deep-Purple-100 bg ti-menu-alt"></span><i class="ti-more-alt"></i><span class="palette-Deep-Purple-200 bg ti-shopping-cart-full"></span><i class="ti-more-alt"></i><span class="palette-Deep-Purple-400 bg ti-gift"></span><i class="ti-more-alt"></i><span class="palette-Deep-Purple-600 bg ti-truck"></span><i class="ti-more-alt"></i><span class="palette-Deep-Purple-800 bg ti-home"></span>Shipping proses of <strong>Robert Langdon</strong> is completed!<small>1m</small></a></li>
      <li><a href="#"><span class="palette-Blue-A100 bg ti-user"></span>Meet new user <strong>Lilian Meirs</strong><small>23m</small></a></li>
      <li><a href="#"><span class="palette-Red-A400 bg ti-cloud-down"></span><strong>Robert</strong> added new request for ne item for refund<small>34m</small></a></li>
      <li><a href="#"><span class="palette-Orange-200 bg ti-menu-alt"></span><i class="ti-more-alt"></i><span class="palette-Orange-400 bg ti-shopping-cart-full"></span><i class="ti-more-alt"></i><span class="palette-Orange-600 bg ti-gift"></span><br>Shipping proses of <strong>Robert Langdon</strong> is completed!<small>40m</small></a></li>
      <li><a href="#"><span class="palette-Amber-500 bg ti-comment-alt"></span>Mike Nilson commented Post<br>
                                            Like this one! Keep going!<small>50m</small></a></li>
      <li><a href="#"><span class="palette-Cyan-300 bg ti-shopping-cart-full"></span>Amazing! <strong>Mike Nilson</strong> just purchased Your item <small>1h</small></a></li>
      <li><a href="#"><span class="palette-Light-Green-500 bg ti-image"></span><strong>Lilian Meirs</strong> Posting new image cover, and just got 2.000 likes<br><img alt="" src="https://source.unsplash.com/category/technology/500x200"><small>1h 12m</small></a></li>
      <li><a href="#"><span class="palette-Amber-500 bg ti-comment-alt"></span>Mike Nilson commented Post<br>
                                              Like this one! Keep going!<small>1h 39</small></a></li>
      <li><a href="#"><span class="palette-Cyan-300 bg ti-shopping-cart-full"></span>Amazing! <strong>Mike Nilson</strong> just purchased Your item<br><img alt="" src="https://source.unsplash.com/category/food/500x200"> <small>1h 45m</small></a></li>
      <li><a href="#"><span class="palette-Cyan-300 bg ti-shopping-cart-full"></span>Amazing! <strong>Mike Nilson</strong> just purchased Your item <small>23m</small></a></li>
      <li><a href="#"><span class="palette-Amber-500 bg ti-comment-alt"></span>Mike Nilson commented Post<br>
                                                Like this one! Keep going!<small>2h</small></a></li>
    </ul>
  </div>
</div>
<!-- End of Right Menu -->
</div>
<!-- end paper bg -->
</div>
</div>

templates/header.html
{% load staticfiles %}

<!-- preloader -->
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>
<!-- End of preloader -->
<div class="off-canvas-wrapper over-flow-hidden">
  <div class="off-canvas-wrapper-inner " data-off-canvas-wrapper>
    <div class="inner-wrap">
      <div id="skin-select">
        <a id="toggle"></a>
        <div class="skin-part">
          <div id="tree-wrap">
            <a href="/">
              <div class="profile"> <img alt="" class="" src="{% static "img/yeti.svg" %}">
                <a href="/"><h3>SmileyLab </h3></a>
              </div>
            </a>
            <div class="side-bar">
              <ul id="menu-showhide" class="topnav slicknav">
                <li>
                  <a id="menu-select" class="tooltip-tip" href="#" title="Dashboard">
                    <i class="palette-Deep-Purple-700 bg ti-desktop"></i>
                    <span>Dashboard</span>
                  </a>
                  <ul>
                      <li><a href="{% url "app:job" %}">Jobs/Status</a></li>
                    <li><a href="#">Numerical Analysis</a></li>
                    <li><a href="#">Visual Analysis</a></li>
                    <li><a href="#">Analytics</a></li>
                    <li><a href="#">Triggers</a></li>
                    <li><a href="#">Bookmarks</a></li>
                    <li><a href="#">Uploads</a></li>
                    <li><a href="#">Links</a></li>
                  </ul>
                </li>
                <li>
                  <a class="tooltip-tip" href="#"> <i class="palette-Indigo-700 bg ti-layout"></i> <span>JOB</span> </a>
                  <ul>
                    <li><a href="{% url "app:job" %}">New Job</a></li>
                    <li><a href="{% url "app:showJobs"%}">Show Jobs</a></li>
                    <li><a href="#">Status</a></li>
                  </ul>
                </li>
                <li>
                  <a class="tooltip-tip" href="#"> <i class="palette-Indigo-700 bg fa fa-bold"></i> <span>BRAND</span> </a>
                  <ul>
                    <li><a href="{% url "app:showBrands"%}">Show Brands</a></li>
                  </ul>
                </li>
                <li>
                  <a class="tooltip-tip" href="#" title="Division"> <i class="intial palette-Blue-700 bg ti-email"></i> <span>Division</span> </a>
                  <ul>
                    <li><a href="{% url "app:division" %}">New Division</a></li>
                    <li><a href="{% url "app:showDivisions"%}">Show Divisions</a></li>
                  </ul>
                </li>
                <li>
                  <a href="#" class="tooltip-tip"> <i class="intial palette-Blue-900 bg ti-write"></i> <span>Standard
                  </span> </a>
                  <ul>
                    <li><a href="{% url "app:standard" %}">New Standards</a></li>
                    <li><a href="{% url "app:showStandards" %}">Show Standards</a></li>
                    <li><a href="{% url "app:showEvalutions" %}">Show Evaluations</a></li>
                    <li><a href="{% url "app:patchStandard" %}">New Brand Color</a></li>
                    <li><a href="{% url "app:patchTolerance" %}">New Patch Tolerance</a></li>
                    <li><a href="{% url "app:showMemberEvaluations" %}">Show Member Evaluation</a></li>
                    <li><a href="{% url "app:showMemberProperty" %}">Show Member Property</a></li>
                  </ul>
                </li>
                <li>
                  <a href="#" class="tooltip-tip">  <i class="intial palette-Teal-600 bg ti-vector"></i>
                      <span>Trend</span>
                    </a>
                </li>
                <li>
                  <a href="#"> <i class="intial palette-Green-700 bg ti-layers-alt"></i> <span>Analytics&nbsp;
                    </a>
                </li>

                <li>
                  <a class="tooltip-tip" href="#" title="Extra"> <i class="intial palette-Orange-700 bg ti-zip"></i> <span>Uploads</span> </a>
                  <ul>
                    <li><a href="{% url "app:upload" %}">New Upload</a></li>
                    <li><a href="{% url "app:showUploads" %}">Show Uploads</a></li>
                    <li><a href="#">Show File Category</a></li>
                  </ul>
                </li>
                <li>
                  <a class="tooltip-tip" href="#" title="Extra"> <i class="palette-Pink-700 bg ti-gift"></i> <span>Bookmarks</span> </a>
                  <ul>
                    <li><a href="{% url "app:bookmark"%}">New Bookmarks</a></li>
                    <li><a href="#">Show Bookmarks</a></li>
                    <li><a href="#">New Bookmarks Category</a></li>
                    <li><a href="#">Show Bookmarks Category</a></li>
                  </ul>
                </li>
                <li>
                  <a class="tooltip-tip" href="#" title="Extra"> <i class="palette-Pink-700 bg ti-gift"></i> <span>Links</span> </a>
                  <ul>
                    <li><a href="{% url "app:link"%}">New Links</a></li>
                    <li><a href="#">Show Links</a></li>
                  </ul>
                </li>
                <li>
                  <a class="tooltip-tip" href="#" title="Extra"> <i class="intial palette-Lime-700 bg ti-harddrives"></i> <span>Others</span> </a>
                  <ul>
                    <li><a href="#">Triggers</a></li>
                    <li><a href="{% url "app:role"%}">New Role</a></li>
                    <li><a href="{% url "app:link"%}">New Links</a></li>
                    <li><a href="#">Show Links</a></li>
                  </ul>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </div>
      <div class="wrap-fluid" id="paper-bg">
  <br><br>

templates/index.html
{% extends "base.html" %} {% load staticfiles %} {% block title %} Home {% endblock title %} {% block content %}
<div class="row" style="margin-top:-20px">
  <div class="large-6 columns">
    <div class="row">
      <a href="{% url "app:showJobs"%}">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-tasks fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/jobs.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">JOBS/STATUS</h6>

                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
      <a href="#">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-pie-chart fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/nume_ana.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Numerical Analysis</h6>

                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
      <a href="#">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-area-chart fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/vis_ana.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Visual Analysis</h6>

                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
      <a href="#">

        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-line-chart fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/ana.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Analytics</h6>

                </div>
              </div>
            </div>
          </div>
        </div>
      </a>

      <!-- <div class="large-6 columns">
        <div class="box palette-White bg">
          <div class="box-header  palette-White bg">
            <div class="pull-right text-white box-tools"> <span class="text-white box-btn"><i class="circle-nest-medium ti-stats-up"></i>
                              </span>&nbsp;&nbsp;&nbsp; </div>
            <h3 class="box-title">
                                <span class="text-white">&nbsp;&nbsp;&nbsp;PAGE VIEWS</span>
                              </h3> </div>
          <div class="box-body no-pad" style="display: block;">
            <div class="events-nest ">
              <div class="wrap-no-pad text-white">
                <h1 class="text-white"><b class="counter-up-fast">294</h1> <span>Users</span>
                <p>65%</p>
                <br> </div>
            </div>
          </div>
        </div>
      </div> -->
    </div>
  </div>

  <div class="large-6 columns">
    <div class="row">

      <a href="#">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-clock-o fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/trigger.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Triggers</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
      <a href="#">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-bookmark fa-3x" aria-hidden="true"></i>

                    <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/bookmark.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Bookmarks</h6>

                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
      <a href="{%url "app:showUploads" %}">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white" >
                  <br>
                  <i class="fa fa-download fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/download.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Uploads</h6>

                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
      <a href="#">
        <div class="large-6 columns">
          <div class="box palette-White bg">
            <div class="box-body no-pad" style="display: block;">
              <div class="events-nest ">
                <div class="wrap-no-pad text-white">
                  <br>
                  <i class="fa fa-link fa-3x" aria-hidden="true"></i>
                  <!-- <img alt="" style="margin-left: auto; margin-right: auto; display: block;" src="{% static "img/templates/links.png" %}" width="50px" height="50px" > -->
                  <br><h6 class="text-white">Links</h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>

</div>
{% endblock content %}

templates/login.html
{% extends "login_base.html" %} {% load staticfiles %} {% block title %} Login {% endblock title %} {% block content %}
<!-- right sidebar wrapper -->
<div class="inner-wrap">
  <div class="wrap-fluid">
    <br>
    <br>
    <!-- Container Begin -->
    <div class="large-5 small-centered columns">
      <div class="profile"> <img alt="" class="" src="{% static "img/yeti.svg" %}">
        <h3>SmileyLab </h3> </div>
      <div class="box bg-white">
        <!-- Profile -->
        <!-- End of Profile -->
        <!-- /.box-header -->
        <div class="box-body " style="display: block;">
          <div class="row">
            <div class="large-12 columns">
              <div class="row">
                <div class="edumix-signup-panel">
                  {% if message %}
                  <p style="color:red;">{{message}}</p>
                  {% endif %}
                  <p class="welcome">Log in with you email account</p>
                  <form method="post" action="{% url "app:index" %}">
                    {% csrf_token %}
                    <div class="row column log-in-form">
                      <label>Username<input type="text" name="uname" placeholder="somebody@example.com"> </label>
                      <label>Password<input type="text" name="pass" placeholder="Password"> </label>
                      <p><input type="submit" value="Login" class="button expanded" /></p>
                    </div>
                  </form>
                  <br>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
        <!-- end .timeline -->
      </div>
      <!-- box -->
    </div>
  </div>
  <!-- End of Container Begin -->
</div>
<!-- end paper bg -->
<div id="gradient" /> {% endblock content %}